x-app-build: &app-build
  build:
    context: .
    dockerfile: docker/app/Dockerfile

services:
  celery:
    <<: *app-build

  api:
    <<: *app-build

  proxy:
    build:
      context: .
      dockerfile: docker/proxy/Dockerfile
